[build]
  command = "CI=false npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/nav"
  to = "/.netlify/functions/nav"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
